services:
  sonarqube:
    image: sonarqube:latest
    container_name: moliceiro-meals-sonarqube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions: